/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ManipulaçãoDeDados.Arquivo;
import ManipulaçãoDeDados.Livro;
import java.util.Objects;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author juliana
 */
public class DadosLivro extends javax.swing.JInternalFrame {

    private boolean alterarNovoIncluir = true;
    
    public DadosLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isnb = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        numEdicao = new javax.swing.JTextField();
        copyringt = new javax.swing.JTextField();
        arquivoDeImagem = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        listaEditora = new javax.swing.JComboBox();
        novoIncluir = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        autoresList = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Dados do Livro");

        jLabel1.setText("ISBN:");

        jLabel2.setText("Título:");

        jLabel3.setText("Número edição:");

        jLabel4.setText("Copyright: ");

        jLabel5.setText("Arquivo de Imagem: ");

        jLabel6.setText("Preço: ");

        jLabel7.setText("Editora: ");

        jLabel8.setText("Autor(es): ");

        listaEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEditoraActionPerformed(evt);
            }
        });

        novoIncluir.setText("Novo");
        novoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoIncluirActionPerformed(evt);
            }
        });

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(autoresList);
        autoresList.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(novoIncluir)
                        .addGap(35, 35, 35)
                        .addComponent(pesquisar)
                        .addGap(48, 48, 48)
                        .addComponent(cancelar))
                    .addComponent(listaEditora, 0, 397, Short.MAX_VALUE)
                    .addComponent(preco)
                    .addComponent(arquivoDeImagem)
                    .addComponent(copyringt)
                    .addComponent(numEdicao)
                    .addComponent(titulo)
                    .addComponent(isnb, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {arquivoDeImagem, copyringt, isnb, listaEditora, numEdicao, preco, titulo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelar, novoIncluir, pesquisar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(isnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(copyringt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(arquivoDeImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(listaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(novoIncluir)
                        .addComponent(pesquisar))
                    .addComponent(cancelar))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaEditoraActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void novoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoIncluirActionPerformed
        
        
        Arquivo autores = new Arquivo("Autores.txt");
        Arquivo editoras = new Arquivo("Editoras.txt");
        
        if(alterarNovoIncluir){
        
            //Preenche Jlist com altores

            DefaultListModel modelo1 = new DefaultListModel();

            autores.listarPorLinha();

            for(int i = 0; i < autores.sizeList(); i++)
                modelo1.addElement(autores.getElementoLista(i));

            autoresList.setModel(modelo1);

            //Preenche JCombo (ou algo assim) com editoras

            JComboBox modelo2 = new JComboBox();

            editoras.listarPorLinha();

            for(int i = 0; i < editoras.sizeList(); i++)
                listaEditora.addItem(editoras.getElementoLista(i));

            alterarNovoIncluir = false;
            novoIncluir.setText("Incluir");
            
        }else{
            
            autores.listarPorLinha();
            editoras.listarPorLinha();

            Arquivo.gravarEmArquivo("Livros.txt", isnb.getText(), false);
            
            Arquivo.gravarEmArquivo("Livros.txt", titulo.getText(), false);
            
            Arquivo.gravarEmArquivo("Livros.txt", numEdicao.getText(), false);
            
            Arquivo.gravarEmArquivo("Livros.txt", copyringt.getText(), false);
            
            Arquivo.gravarEmArquivo("Livros.txt", arquivoDeImagem.getText(), false);
            
            Arquivo.gravarEmArquivo("Livros.txt", preco.getText(), false);
            
            Arquivo.gravarEmArquivo("Livros.txt", editoras.getElementoLista(listaEditora.getSelectedIndex()), false);
            
            int[] indiceSelecionadoAutores = autoresList.getSelectedIndices();
            Integer a = autoresList.getSelectedIndices().length;
            Arquivo.gravarEmArquivo("Livros.txt", a.toString(), false);
            
            for(int j = 0; j < autoresList.getSelectedIndices().length; j++){
                Arquivo.gravarEmArquivo("Livros.txt", editoras.getElementoLista(autoresList.getSelectedIndices()[j]), false);
            }
            
            limpar();
        }
        
        
        
        
    }//GEN-LAST:event_novoIncluirActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        
        Arquivo autores = new Arquivo("Autores.txt");//Obj que vai me permitir ter acesso ao Autores.txt
        autores.listarPorLinha();//Crio lista a partir do arquivo
        
        Arquivo editoras = new Arquivo("Editoras.txt");//Obj que vai me permitir ter acesso ao Etidoras.txt
        editoras.listarPorLinha();//Crio lista a partir do arquivo
        
        Arquivo a = new Arquivo("Livros.txt");//Obj que vai me permitir ter acesso ao Livros.txt
        a.listarLivros();//Crio lista a partir do arquivo
        
        
        Livro c = new  Livro();//Crio obj livro
        
        //ler atributos
        c.setIsnb(isnb.getText());
        c.setTitulo(titulo.getText());
        c.setNumEdicao(numEdicao.getText());
        c.setCopyringt(copyringt.getText());
        c.setArquivoDeImagem(arquivoDeImagem.getText());
        c.setPreco(preco.getText());
        c.setEditora(editoras.getElementoLista(listaEditora.getSelectedIndex()));

        //matriz de indice de autores
        int[] indiceSelecionadoAutores = autoresList.getSelectedIndices();
        
        //add nome de autores a string com nome de autores
        String[] autoresSelecionados = new String[autoresList.getSelectedIndices().length];          
        for(int i = 0; i < autoresList.getSelectedIndices().length; i++){
            autoresSelecionados[i] = autores.getElementoLista(indiceSelecionadoAutores[i]);
        }

        //add string com nome de altores ao obj c
        c.setAutores(autoresSelecionados);//add atores ao objeto
        
        //recebo um vetor de objs livros
        Livro[] biblioteca = a.getListaLivros();
        
        //pego o indice de qual parece ser
        int pesquisa = c.corespondecia(biblioteca);
        
        String todosOsAutores = biblioteca[pesquisa].getAutores()[0] + "\n";
        
        for(int i = 1; i < biblioteca[pesquisa].getAutores().length; i++){
            todosOsAutores += biblioteca[pesquisa].getAutores()[i] + "\n";
        }
        
        JOptionPane.showMessageDialog(null, "Encontramos:" + 
                biblioteca[pesquisa].getTitulo() + "\n" +
                "Da editora: "+biblioteca[pesquisa].getEditora()+ "\n" +
                "Por: " + biblioteca[pesquisa].getPreco()+ "\n" +
                "Com a licença: " + biblioteca[pesquisa].getCopyringt()+ "\n" + 
                "ISNBS: " + biblioteca[pesquisa].getIsnb()+ "\n" +
                "Edição: " + biblioteca[pesquisa].getNumEdicao()+ "\n" +
                "Autores: \n" + todosOsAutores);
        
        //printo
        
        
    }//GEN-LAST:event_pesquisarActionPerformed

    public void limpar(){
        
        isnb.setText("");
        titulo.setText("");
        numEdicao.setText("");
        copyringt.setText("");
        arquivoDeImagem.setText("");
        preco.setText("");
    }//end limpar
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arquivoDeImagem;
    private javax.swing.JList<String> autoresList;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField copyringt;
    private javax.swing.JTextField isnb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listaEditora;
    private javax.swing.JButton novoIncluir;
    private javax.swing.JTextField numEdicao;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
